-- Invoices owned by the billing service.
-- Numbering is sequential and generated by the database, so concurrent
-- creations never share a number.
CREATE SEQUENCE invoice_number_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE invoices (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    number     BIGINT      NOT NULL DEFAULT nextval('invoice_number_seq'),
    status     TEXT        NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    printed_at TIMESTAMPTZ,

    CONSTRAINT invoices_number_unique CHECK (number > 0),
    CONSTRAINT invoices_status_valid  CHECK (status IN ('OPEN', 'PRINTING', 'CLOSED'))
);

CREATE UNIQUE INDEX invoices_number_unique_idx ON invoices (number);

-- Items reference products by id and keep a snapshot of code and description,
-- so an invoice still prints correctly if the product is renamed later.
CREATE TABLE invoice_items (
    id                  UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id          UUID    NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    product_id          UUID    NOT NULL,
    product_code        TEXT    NOT NULL,
    product_description TEXT    NOT NULL,
    quantity            INTEGER NOT NULL,

    CONSTRAINT invoice_items_quantity_positive CHECK (quantity > 0)
);

-- A product appears at most once per invoice; quantities are summed instead.
CREATE UNIQUE INDEX invoice_items_unique_product_idx ON invoice_items (invoice_id, product_id);
CREATE INDEX invoice_items_invoice_idx ON invoice_items (invoice_id);
