package billing_test

import (
	"context"
	"errors"
	"sync"
	"testing"

	"github.com/google/uuid"
	"github.com/thiagodias/korp-invoices/internal/billing"
	"github.com/thiagodias/korp-invoices/internal/platform/postgres/pgtest"
)

func newTestStore(t *testing.T) (context.Context, *billing.Store) {
	t.Helper()

	ctx, pool := pgtest.Pool(t, "BILLING_TEST_DATABASE_URL", billing.MigrationsFS, billing.MigrationsDir)
	return ctx, billing.NewStore(pool)
}

func sampleItems() []billing.Item {
	return []billing.Item{
		{ProductID: uuid.New(), ProductCode: "P-1", ProductDescription: "Steel bolt", Quantity: 2},
		{ProductID: uuid.New(), ProductCode: "P-2", ProductDescription: "Hammer", Quantity: 3},
	}
}

func TestStoreCreateStartsOpenWithSequentialNumbers(t *testing.T) {
	ctx, store := newTestStore(t)

	first, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	second, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	if first.Status != billing.StatusOpen {
		t.Errorf("status = %s, want %s", first.Status, billing.StatusOpen)
	}
	if first.Number != 1 {
		t.Errorf("first number = %d, want 1", first.Number)
	}
	if second.Number != first.Number+1 {
		t.Errorf("second number = %d, want %d", second.Number, first.Number+1)
	}
	if first.ID == uuid.Nil || first.CreatedAt.IsZero() {
		t.Error("invoice identity or timestamps are missing")
	}
	if first.PrintedAt != nil {
		t.Errorf("PrintedAt = %v, want nil on a new invoice", first.PrintedAt)
	}
}

func TestStoreCreatePersistsItems(t *testing.T) {
	ctx, store := newTestStore(t)
	items := sampleItems()

	created, err := store.Create(ctx, items)
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	if len(created.Items) != 2 {
		t.Fatalf("items = %d, want 2", len(created.Items))
	}
	for _, item := range created.Items {
		if item.ID == uuid.Nil {
			t.Error("item id is empty, want one generated by the database")
		}
	}

	loaded, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if len(loaded.Items) != 2 {
		t.Fatalf("loaded items = %d, want 2", len(loaded.Items))
	}
	if loaded.Items[0].ProductCode != "P-1" || loaded.Items[0].Quantity != 2 {
		t.Errorf("loaded item = %+v, want the stored values", loaded.Items[0])
	}
	if loaded.Items[0].ProductDescription != "Steel bolt" {
		t.Errorf("description = %q, want the snapshot taken at creation", loaded.Items[0].ProductDescription)
	}
}

func TestStoreCreateRejectsInvalidItemsWithoutLeavingAnInvoice(t *testing.T) {
	ctx, store := newTestStore(t)

	_, err := store.Create(ctx, []billing.Item{
		{ProductID: uuid.New(), ProductCode: "P-1", ProductDescription: "Steel bolt", Quantity: 0},
	})
	if err == nil {
		t.Fatal("Create() returned no error for a zero quantity, want one")
	}

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(invoices.Items) != 0 {
		t.Errorf("invoices = %d, want 0 (the failed creation must roll back)", len(invoices.Items))
	}
}

func TestStoreGetByIDReportsMissingInvoice(t *testing.T) {
	ctx, store := newTestStore(t)

	if _, err := store.GetByID(ctx, uuid.New()); !errors.Is(err, billing.ErrInvoiceNotFound) {
		t.Errorf("GetByID() error = %v, want ErrInvoiceNotFound", err)
	}
}

func TestStoreListOrdersByNewestNumberAndLoadsItems(t *testing.T) {
	ctx, store := newTestStore(t)
	first, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	second, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(invoices.Items) != 2 {
		t.Fatalf("invoices = %d, want 2", len(invoices.Items))
	}
	if invoices.Items[0].ID != second.ID || invoices.Items[1].ID != first.ID {
		t.Error("invoices are not ordered from the newest to the oldest")
	}
	for _, invoice := range invoices.Items {
		if len(invoice.Items) != 2 {
			t.Errorf("invoice %d has %d items, want 2", invoice.Number, len(invoice.Items))
		}
	}
}

func TestStoreListFiltersByStatus(t *testing.T) {
	ctx, store := newTestStore(t)
	if _, err := store.Create(ctx, sampleItems()); err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	open, err := store.List(ctx, billing.Query{Status: string(billing.StatusOpen)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(open.Items) != 1 {
		t.Errorf("open invoices = %d, want 1", len(open.Items))
	}

	closed, err := store.List(ctx, billing.Query{Status: string(billing.StatusClosed)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(closed.Items) != 0 {
		t.Errorf("closed invoices = %d, want 0", len(closed.Items))
	}
}

func TestStoreListReturnsEmptySlice(t *testing.T) {
	ctx, store := newTestStore(t)

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if invoices.Items == nil {
		t.Fatal("List() returned nil items, want an empty slice")
	}
}

// Numbering must stay unique and gap free under concurrent creations, since
// the sequence is what guarantees it.
func TestStoreCreateAssignsUniqueNumbersConcurrently(t *testing.T) {
	ctx, store := newTestStore(t)

	const creations = 10
	var (
		wg      sync.WaitGroup
		mu      sync.Mutex
		numbers = map[int64]bool{}
		failed  []error
	)

	wg.Add(creations)
	for range creations {
		go func() {
			defer wg.Done()

			invoice, err := store.Create(ctx, sampleItems())

			mu.Lock()
			defer mu.Unlock()
			if err != nil {
				failed = append(failed, err)
				return
			}
			if numbers[invoice.Number] {
				failed = append(failed, errors.New("duplicated invoice number"))
				return
			}
			numbers[invoice.Number] = true
		}()
	}
	wg.Wait()

	if len(failed) > 0 {
		t.Fatalf("concurrent creations failed: %v", failed)
	}
	if len(numbers) != creations {
		t.Errorf("distinct numbers = %d, want %d", len(numbers), creations)
	}
}

func TestStoreListPagesFromTheNewestInvoice(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 5 {
		if _, err := store.Create(ctx, sampleItems()); err != nil {
			t.Fatalf("Create() returned error: %v", err)
		}
	}

	first, err := store.List(ctx, billing.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(first.Items) != 2 || first.Items[0].Number != 5 || first.Items[1].Number != 4 {
		t.Fatalf("first page = %v, want invoices 5 and 4", numbersOf(first.Items))
	}
	if first.NextCursor == "" {
		t.Fatal("first page has no cursor, want one")
	}
	// Items are loaded for every invoice on the page, not only the first.
	for _, invoice := range first.Items {
		if len(invoice.Items) != 2 {
			t.Errorf("invoice %d has %d items, want 2", invoice.Number, len(invoice.Items))
		}
	}

	second, err := store.List(ctx, billing.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 2 || second.Items[0].Number != 3 {
		t.Fatalf("second page = %v, want invoices 3 and 2", numbersOf(second.Items))
	}

	last, err := store.List(ctx, billing.Query{Limit: 2, Cursor: second.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(last.Items) != 1 || last.Items[0].Number != 1 {
		t.Fatalf("last page = %v, want invoice 1", numbersOf(last.Items))
	}
	if last.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", last.NextCursor)
	}
}

// Invoices issued while someone is paging appear on the first page next time,
// and never shift what was already read.
func TestStoreListIsStableWhenInvoicesAreIssuedWhilePaging(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 3 {
		if _, err := store.Create(ctx, sampleItems()); err != nil {
			t.Fatalf("Create() returned error: %v", err)
		}
	}

	first, err := store.List(ctx, billing.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if _, err := store.Create(ctx, sampleItems()); err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	second, err := store.List(ctx, billing.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 1 || second.Items[0].Number != 1 {
		t.Errorf("second page = %v, want only invoice 1", numbersOf(second.Items))
	}
}

func TestStoreListRejectsACursorItDidNotProduce(t *testing.T) {
	ctx, store := newTestStore(t)

	if _, err := store.List(ctx, billing.Query{Cursor: "not-a-cursor"}); err == nil {
		t.Error("List() accepted a made up cursor, want an error")
	}
}

func numbersOf(invoices []billing.Invoice) []int64 {
	numbers := make([]int64, 0, len(invoices))
	for _, invoice := range invoices {
		numbers = append(numbers, invoice.Number)
	}
	return numbers
}
