package billing_test

import (
	"context"
	"errors"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/thiagodias/korp-invoices/internal/billing"
	"github.com/thiagodias/korp-invoices/internal/platform/pagination"
	"github.com/thiagodias/korp-invoices/internal/platform/postgres/pgtest"
)

// testPools keeps the pool of each test at hand, so a test can seed or age
// rows without the store getting in the way.
var testPools = map[context.Context]*pgxpool.Pool{}

func newTestStore(t *testing.T) (context.Context, *billing.Store) {
	t.Helper()

	ctx, pool := pgtest.Pool(t, "BILLING_TEST_DATABASE_URL", billing.MigrationsFS, billing.MigrationsDir)
	testPools[ctx] = pool
	t.Cleanup(func() { delete(testPools, ctx) })

	return ctx, billing.NewStore(pool)
}

func poolOf(t *testing.T, ctx context.Context) *pgxpool.Pool {
	t.Helper()

	pool, ok := testPools[ctx]
	if !ok {
		t.Fatal("no pool for this test")
	}
	return pool
}

func sampleItems() []billing.Item {
	return []billing.Item{
		{ProductID: uuid.New(), ProductCode: "P-1", ProductDescription: "Steel bolt", Quantity: 2},
		{ProductID: uuid.New(), ProductCode: "P-2", ProductDescription: "Hammer", Quantity: 3},
	}
}

func TestStoreCreateStartsOpenWithSequentialNumbers(t *testing.T) {
	ctx, store := newTestStore(t)

	first, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	second, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	if first.Status != billing.StatusOpen {
		t.Errorf("status = %s, want %s", first.Status, billing.StatusOpen)
	}
	if first.Number != 1 {
		t.Errorf("first number = %d, want 1", first.Number)
	}
	if second.Number != first.Number+1 {
		t.Errorf("second number = %d, want %d", second.Number, first.Number+1)
	}
	if first.ID == uuid.Nil || first.CreatedAt.IsZero() {
		t.Error("invoice identity or timestamps are missing")
	}
	if first.PrintedAt != nil {
		t.Errorf("PrintedAt = %v, want nil on a new invoice", first.PrintedAt)
	}
}

func TestStoreCreatePersistsItems(t *testing.T) {
	ctx, store := newTestStore(t)
	items := sampleItems()

	created, err := store.Create(ctx, items)
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	if len(created.Items) != 2 {
		t.Fatalf("items = %d, want 2", len(created.Items))
	}
	for _, item := range created.Items {
		if item.ID == uuid.Nil {
			t.Error("item id is empty, want one generated by the database")
		}
	}

	loaded, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if len(loaded.Items) != 2 {
		t.Fatalf("loaded items = %d, want 2", len(loaded.Items))
	}
	if loaded.Items[0].ProductCode != "P-1" || loaded.Items[0].Quantity != 2 {
		t.Errorf("loaded item = %+v, want the stored values", loaded.Items[0])
	}
	if loaded.Items[0].ProductDescription != "Steel bolt" {
		t.Errorf("description = %q, want the snapshot taken at creation", loaded.Items[0].ProductDescription)
	}
}

func TestStoreCreateRejectsInvalidItemsWithoutLeavingAnInvoice(t *testing.T) {
	ctx, store := newTestStore(t)

	_, err := store.Create(ctx, []billing.Item{
		{ProductID: uuid.New(), ProductCode: "P-1", ProductDescription: "Steel bolt", Quantity: 0},
	})
	if err == nil {
		t.Fatal("Create() returned no error for a zero quantity, want one")
	}

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(invoices.Items) != 0 {
		t.Errorf("invoices = %d, want 0 (the failed creation must roll back)", len(invoices.Items))
	}
}

func TestStoreGetByIDReportsMissingInvoice(t *testing.T) {
	ctx, store := newTestStore(t)

	if _, err := store.GetByID(ctx, uuid.New()); !errors.Is(err, billing.ErrInvoiceNotFound) {
		t.Errorf("GetByID() error = %v, want ErrInvoiceNotFound", err)
	}
}

func TestStoreListOrdersByNewestNumberAndLoadsItems(t *testing.T) {
	ctx, store := newTestStore(t)
	first, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	second, err := store.Create(ctx, sampleItems())
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(invoices.Items) != 2 {
		t.Fatalf("invoices = %d, want 2", len(invoices.Items))
	}
	if invoices.Items[0].ID != second.ID || invoices.Items[1].ID != first.ID {
		t.Error("invoices are not ordered from the newest to the oldest")
	}
	for _, invoice := range invoices.Items {
		if len(invoice.Items) != 2 {
			t.Errorf("invoice %d has %d items, want 2", invoice.Number, len(invoice.Items))
		}
	}
}

func TestStoreListFiltersByStatus(t *testing.T) {
	ctx, store := newTestStore(t)
	if _, err := store.Create(ctx, sampleItems()); err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	open, err := store.List(ctx, billing.Query{Statuses: []string{string(billing.StatusOpen)}})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(open.Items) != 1 {
		t.Errorf("open invoices = %d, want 1", len(open.Items))
	}

	closed, err := store.List(ctx, billing.Query{Statuses: []string{string(billing.StatusClosed)}})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(closed.Items) != 0 {
		t.Errorf("closed invoices = %d, want 0", len(closed.Items))
	}
}

func TestStoreListReturnsEmptySlice(t *testing.T) {
	ctx, store := newTestStore(t)

	invoices, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if invoices.Items == nil {
		t.Fatal("List() returned nil items, want an empty slice")
	}
}

// Numbering must stay unique and gap free under concurrent creations, since
// the sequence is what guarantees it.
func TestStoreCreateAssignsUniqueNumbersConcurrently(t *testing.T) {
	ctx, store := newTestStore(t)

	const creations = 10
	var (
		wg      sync.WaitGroup
		mu      sync.Mutex
		numbers = map[int64]bool{}
		failed  []error
	)

	wg.Add(creations)
	for range creations {
		go func() {
			defer wg.Done()

			invoice, err := store.Create(ctx, sampleItems())

			mu.Lock()
			defer mu.Unlock()
			if err != nil {
				failed = append(failed, err)
				return
			}
			if numbers[invoice.Number] {
				failed = append(failed, errors.New("duplicated invoice number"))
				return
			}
			numbers[invoice.Number] = true
		}()
	}
	wg.Wait()

	if len(failed) > 0 {
		t.Fatalf("concurrent creations failed: %v", failed)
	}
	if len(numbers) != creations {
		t.Errorf("distinct numbers = %d, want %d", len(numbers), creations)
	}
}

func TestStoreListPagesFromTheNewestInvoice(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 5 {
		if _, err := store.Create(ctx, sampleItems()); err != nil {
			t.Fatalf("Create() returned error: %v", err)
		}
	}

	first, err := store.List(ctx, billing.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(first.Items) != 2 || first.Items[0].Number != 5 || first.Items[1].Number != 4 {
		t.Fatalf("first page = %v, want invoices 5 and 4", numbersOf(first.Items))
	}
	if first.NextCursor == "" {
		t.Fatal("first page has no cursor, want one")
	}
	// Items are loaded for every invoice on the page, not only the first.
	for _, invoice := range first.Items {
		if len(invoice.Items) != 2 {
			t.Errorf("invoice %d has %d items, want 2", invoice.Number, len(invoice.Items))
		}
	}

	second, err := store.List(ctx, billing.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 2 || second.Items[0].Number != 3 {
		t.Fatalf("second page = %v, want invoices 3 and 2", numbersOf(second.Items))
	}

	last, err := store.List(ctx, billing.Query{Limit: 2, Cursor: second.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(last.Items) != 1 || last.Items[0].Number != 1 {
		t.Fatalf("last page = %v, want invoice 1", numbersOf(last.Items))
	}
	if last.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", last.NextCursor)
	}
}

// Invoices issued while someone is paging appear on the first page next time,
// and never shift what was already read.
func TestStoreListIsStableWhenInvoicesAreIssuedWhilePaging(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 3 {
		if _, err := store.Create(ctx, sampleItems()); err != nil {
			t.Fatalf("Create() returned error: %v", err)
		}
	}

	first, err := store.List(ctx, billing.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if _, err := store.Create(ctx, sampleItems()); err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	second, err := store.List(ctx, billing.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 1 || second.Items[0].Number != 1 {
		t.Errorf("second page = %v, want only invoice 1", numbersOf(second.Items))
	}
}

func TestStoreListRejectsACursorItDidNotProduce(t *testing.T) {
	ctx, store := newTestStore(t)

	if _, err := store.List(ctx, billing.Query{Cursor: "not-a-cursor"}); err == nil {
		t.Error("List() accepted a made up cursor, want an error")
	}
}

func numbersOf(invoices []billing.Invoice) []int64 {
	numbers := make([]int64, 0, len(invoices))
	for _, invoice := range invoices {
		numbers = append(numbers, invoice.Number)
	}
	return numbers
}

func createInvoiceWith(t *testing.T, ctx context.Context, store *billing.Store, code string, quantity int) billing.Invoice {
	t.Helper()

	invoice, err := store.Create(ctx, []billing.Item{
		{ProductID: uuid.New(), ProductCode: code, ProductDescription: "Product " + code, Quantity: quantity},
	})
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	return invoice
}

func TestStoreListFiltersByNumber(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 3 {
		createInvoiceWith(t, ctx, store, "P-1", 1)
	}

	number := int64(2)
	page, err := store.List(ctx, billing.Query{Number: &number})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 1 || page.Items[0].Number != 2 {
		t.Errorf("page = %v, want only invoice 2", numbersOf(page.Items))
	}
}

func TestStoreListFiltersBySeveralStatusesAtOnce(t *testing.T) {
	ctx, store := newTestStore(t)
	open := createInvoiceWith(t, ctx, store, "P-1", 1)
	printing := createInvoiceWith(t, ctx, store, "P-1", 1)
	if _, err := store.StartPrinting(ctx, printing.ID); err != nil {
		t.Fatalf("StartPrinting() returned error: %v", err)
	}

	page, err := store.List(ctx, billing.Query{Statuses: []string{"OPEN", "PRINTING"}})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 2 {
		t.Fatalf("page = %v, want both invoices", numbersOf(page.Items))
	}

	onlyPrinting, err := store.List(ctx, billing.Query{Statuses: []string{"PRINTING"}})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(onlyPrinting.Items) != 1 || onlyPrinting.Items[0].ID != printing.ID {
		t.Errorf("page = %v, want the invoice being printed", numbersOf(onlyPrinting.Items))
	}
	_ = open
}

func TestStoreListFiltersByIssueDate(t *testing.T) {
	ctx, store := newTestStore(t)
	old := createInvoiceWith(t, ctx, store, "P-1", 1)
	recent := createInvoiceWith(t, ctx, store, "P-1", 1)

	// Age the first invoice so the two fall on different days.
	pool := poolOf(t, ctx)
	if _, err := pool.Exec(ctx, `UPDATE invoices SET created_at = now() - interval '10 days' WHERE id = $1`, old.ID); err != nil {
		t.Fatalf("age invoice: %v", err)
	}

	from := time.Now().Add(-24 * time.Hour)
	page, err := store.List(ctx, billing.Query{CreatedFrom: &from})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 1 || page.Items[0].ID != recent.ID {
		t.Errorf("page = %v, want only the recent invoice", numbersOf(page.Items))
	}

	to := time.Now().Add(-48 * time.Hour)
	older, err := store.List(ctx, billing.Query{CreatedTo: &to})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(older.Items) != 1 || older.Items[0].ID != old.ID {
		t.Errorf("page = %v, want only the old invoice", numbersOf(older.Items))
	}
}

func TestStoreListFindsTheInvoicesThatUsedAProduct(t *testing.T) {
	ctx, store := newTestStore(t)
	wanted := billing.Item{
		ProductID:          uuid.New(),
		ProductCode:        "BOLT-1",
		ProductDescription: "Steel bolt",
		Quantity:           2,
	}

	withProduct, err := store.Create(ctx, []billing.Item{wanted})
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	createInvoiceWith(t, ctx, store, "HAMMER-1", 1)

	byID, err := store.List(ctx, billing.Query{ProductID: &wanted.ProductID})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(byID.Items) != 1 || byID.Items[0].ID != withProduct.ID {
		t.Errorf("page = %v, want the invoice that used the product", numbersOf(byID.Items))
	}

	byCode, err := store.List(ctx, billing.Query{ProductCode: "bolt-1"})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(byCode.Items) != 1 || byCode.Items[0].ID != withProduct.ID {
		t.Errorf("page = %v, want the lookup by code to ignore casing", numbersOf(byCode.Items))
	}
}

// An invoice with two lines of the same product must not come back twice.
func TestStoreListDoesNotRepeatInvoicesWithSeveralItems(t *testing.T) {
	ctx, store := newTestStore(t)
	first := uuid.New()
	second := uuid.New()

	if _, err := store.Create(ctx, []billing.Item{
		{ProductID: first, ProductCode: "P-1", ProductDescription: "One", Quantity: 1},
		{ProductID: second, ProductCode: "P-2", ProductDescription: "Two", Quantity: 1},
	}); err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}

	page, err := store.List(ctx, billing.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 1 {
		t.Errorf("page = %v, want a single invoice", numbersOf(page.Items))
	}
}

func TestStoreListSeparatesInvoicesThatNeedAttention(t *testing.T) {
	ctx, store := newTestStore(t)
	healthy := createInvoiceWith(t, ctx, store, "P-1", 1)
	failed := createInvoiceWith(t, ctx, store, "P-2", 1)

	if _, err := store.StartPrinting(ctx, failed.ID); err != nil {
		t.Fatalf("StartPrinting() returned error: %v", err)
	}
	if _, err := store.ReopenStalePrintings(ctx, 0, "print_timeout", "No answer in time."); err != nil {
		t.Fatalf("ReopenStalePrintings() returned error: %v", err)
	}

	yes := true
	needAttention, err := store.List(ctx, billing.Query{HasFailure: &yes})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(needAttention.Items) != 1 || needAttention.Items[0].ID != failed.ID {
		t.Errorf("page = %v, want the invoice whose print failed", numbersOf(needAttention.Items))
	}

	no := false
	fine, err := store.List(ctx, billing.Query{HasFailure: &no})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(fine.Items) != 1 || fine.Items[0].ID != healthy.ID {
		t.Errorf("page = %v, want the invoice with nothing wrong", numbersOf(fine.Items))
	}
}

func TestStoreListCombinesFiltersAndPaging(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 5 {
		createInvoiceWith(t, ctx, store, "BOLT-1", 1)
	}
	createInvoiceWith(t, ctx, store, "HAMMER-1", 1)

	query := billing.Query{Statuses: []string{"OPEN"}, ProductCode: "BOLT-1", Limit: 2}

	first, err := store.List(ctx, query)
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(first.Items) != 2 || first.NextCursor == "" {
		t.Fatalf("first page = %v, want two invoices and a cursor", numbersOf(first.Items))
	}

	query.Cursor = first.NextCursor
	second, err := store.List(ctx, query)
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	query.Cursor = second.NextCursor
	third, err := store.List(ctx, query)
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	seen := append(append(numbersOf(first.Items), numbersOf(second.Items)...), numbersOf(third.Items)...)
	if len(seen) != 5 {
		t.Errorf("paged through %v, want the five bolt invoices and not the hammer one", seen)
	}
	if third.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty after the last match", third.NextCursor)
	}
}

func TestStoreListReadsTheOldestFirstWhenAsked(t *testing.T) {
	ctx, store := newTestStore(t)
	for range 3 {
		createInvoiceWith(t, ctx, store, "P-1", 1)
	}

	page, err := store.List(ctx, billing.Query{Order: pagination.Ascending, Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if numbers := numbersOf(page.Items); len(numbers) != 2 || numbers[0] != 1 || numbers[1] != 2 {
		t.Fatalf("page = %v, want invoices 1 and 2", numbers)
	}

	next, err := store.List(ctx, billing.Query{Order: pagination.Ascending, Limit: 2, Cursor: page.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if numbers := numbersOf(next.Items); len(numbers) != 1 || numbers[0] != 3 {
		t.Errorf("second page = %v, want invoice 3", numbers)
	}
}

// Filtering a long history must still read a single page.
func TestStoreListReadsOnlyOnePageOfALongHistory(t *testing.T) {
	ctx, store := newTestStore(t)
	pool := poolOf(t, ctx)

	if _, err := pool.Exec(ctx, `
		INSERT INTO invoices (status, created_at)
		SELECT CASE WHEN number % 3 = 0 THEN 'CLOSED' ELSE 'OPEN' END,
		       now() - (number || ' minutes')::interval
		FROM generate_series(1, 5000) AS number`); err != nil {
		t.Fatalf("seed invoices: %v", err)
	}
	if _, err := pool.Exec(ctx, `ANALYZE invoices`); err != nil {
		t.Fatalf("analyze invoices: %v", err)
	}

	page, err := store.List(ctx, billing.Query{Statuses: []string{"OPEN"}, Limit: 20})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 20 {
		t.Fatalf("page = %d invoices, want 20 out of thousands", len(page.Items))
	}

	plan := explain(t, ctx, pool, `
		SELECT id FROM invoices
		WHERE TRUE AND status = ANY(ARRAY['OPEN'])
		ORDER BY number DESC
		LIMIT 21`)
	if strings.Contains(plan, "Seq Scan") {
		t.Errorf("filtering by status reads every invoice:\n%s", plan)
	}
}

func explain(t *testing.T, ctx context.Context, pool *pgxpool.Pool, statement string) string {
	t.Helper()

	rows, err := pool.Query(ctx, "EXPLAIN "+statement)
	if err != nil {
		t.Fatalf("explain: %v", err)
	}
	defer rows.Close()

	var plan strings.Builder
	for rows.Next() {
		var line string
		if err := rows.Scan(&line); err != nil {
			t.Fatalf("read plan: %v", err)
		}
		plan.WriteString(line)
		plan.WriteString("\n")
	}
	return plan.String()
}
