package stock_test

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/thiagodias/korp-invoices/internal/platform/postgres/pgtest"
	"github.com/thiagodias/korp-invoices/internal/stock"
)

func newTestStore(t *testing.T) (context.Context, *stock.Store, *pgxpool.Pool) {
	t.Helper()

	ctx, pool := pgtest.Pool(t, "STOCK_TEST_DATABASE_URL", stock.MigrationsFS, stock.MigrationsDir)
	return ctx, stock.NewStore(pool), pool
}

func createProduct(t *testing.T, ctx context.Context, store *stock.Store, code, description string, balance int) stock.Product {
	t.Helper()

	product, err := stock.NewProduct(code, description, balance)
	if err != nil {
		t.Fatalf("NewProduct() returned error: %v", err)
	}
	created, err := store.Create(ctx, product)
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	return created
}

func TestStoreCreateAssignsIdentityAndTimestamps(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	if created.ID == uuid.Nil {
		t.Error("ID is empty, want one generated by the database")
	}
	if created.CreatedAt.IsZero() || created.UpdatedAt.IsZero() {
		t.Error("timestamps are empty, want them filled by the database")
	}
	if created.Code != "P-1" || created.Description != "Steel bolt" || created.Balance != 10 {
		t.Errorf("created = %+v, want the submitted values", created)
	}
}

func TestStoreCreateRejectsDuplicatedCodeIgnoringCase(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	duplicated, err := stock.NewProduct("p-1", "Another bolt", 5)
	if err != nil {
		t.Fatalf("NewProduct() returned error: %v", err)
	}

	if _, err := store.Create(ctx, duplicated); !errors.Is(err, stock.ErrDuplicatedCode) {
		t.Fatalf("Create() error = %v, want ErrDuplicatedCode", err)
	}
}

func TestStoreCreateRejectsNegativeBalanceAtDatabaseLevel(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	// Bypassing the domain constructor proves the database refuses invalid
	// data even if a future code path forgets to validate it.
	_, err := store.Create(ctx, stock.Product{Code: "P-9", Description: "Broken", Balance: -1})
	if err == nil {
		t.Fatal("Create() returned no error for a negative balance, want one")
	}
}

func TestStoreGetByIDAndCode(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	byID, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if byID.ID != created.ID {
		t.Errorf("GetByID() = %v, want %v", byID.ID, created.ID)
	}

	byCode, err := store.GetByCode(ctx, "p-1")
	if err != nil {
		t.Fatalf("GetByCode() returned error: %v", err)
	}
	if byCode.ID != created.ID {
		t.Errorf("GetByCode() = %v, want %v", byCode.ID, created.ID)
	}
}

func TestStoreGetReportsMissingProduct(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	if _, err := store.GetByID(ctx, uuid.New()); !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("GetByID() error = %v, want ErrProductNotFound", err)
	}
	if _, err := store.GetByCode(ctx, "missing"); !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("GetByCode() error = %v, want ErrProductNotFound", err)
	}
}

func TestStoreUpdate(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	created.Description = "Stainless bolt"
	created.Balance = 42

	updated, err := store.Update(ctx, created)
	if err != nil {
		t.Fatalf("Update() returned error: %v", err)
	}
	if updated.Description != "Stainless bolt" || updated.Balance != 42 {
		t.Errorf("updated = %+v, want the new values", updated)
	}
	if !updated.UpdatedAt.After(created.CreatedAt) && !updated.UpdatedAt.Equal(created.CreatedAt) {
		t.Errorf("UpdatedAt = %v, want it refreshed", updated.UpdatedAt)
	}

	stored, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if stored.Description != "Stainless bolt" || stored.Balance != 42 {
		t.Errorf("stored = %+v, want the new values persisted", stored)
	}
}

func TestStoreUpdateReportsMissingProduct(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	_, err := store.Update(ctx, stock.Product{ID: uuid.New(), Description: "Ghost", Balance: 1})
	if !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("Update() error = %v, want ErrProductNotFound", err)
	}
}

func TestStoreListOrdersByCodeAndFilters(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "B-2", "Hammer", 3)
	createProduct(t, ctx, store, "a-1", "Steel bolt", 10)
	createProduct(t, ctx, store, "C-3", "Wrench", 7)

	all, err := store.List(ctx, stock.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	wantOrder := []string{"a-1", "B-2", "C-3"}
	if len(all.Items) != len(wantOrder) {
		t.Fatalf("List() returned %d products, want %d", len(all.Items), len(wantOrder))
	}
	for i, code := range wantOrder {
		if all.Items[i].Code != code {
			t.Errorf("product %d = %q, want %q", i, all.Items[i].Code, code)
		}
	}

	filtered, err := store.List(ctx, stock.Query{Search: "bolt"})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(filtered.Items) != 1 || filtered.Items[0].Code != "a-1" {
		t.Errorf("List(bolt) = %+v, want only the bolt product", filtered.Items)
	}

	byCode, err := store.List(ctx, stock.Query{Search: "c-3"})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(byCode.Items) != 1 || byCode.Items[0].Code != "C-3" {
		t.Errorf("List(c-3) = %+v, want only the wrench product", byCode.Items)
	}
}

func TestStoreListReturnsEmptySliceWhenThereAreNoProducts(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	page, err := store.List(ctx, stock.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if page.Items == nil {
		t.Fatal("List() returned nil items, want an empty slice")
	}
	if len(page.Items) != 0 {
		t.Errorf("List() returned %d products, want 0", len(page.Items))
	}
	if page.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", page.NextCursor)
	}
}

func TestStoreFindByIDs(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	first := createProduct(t, ctx, store, "A-1", "Steel bolt", 10)
	second := createProduct(t, ctx, store, "B-2", "Hammer", 3)
	createProduct(t, ctx, store, "C-3", "Wrench", 7)

	found, err := store.FindByIDs(ctx, []uuid.UUID{second.ID, first.ID, uuid.New()})
	if err != nil {
		t.Fatalf("FindByIDs() returned error: %v", err)
	}
	if len(found) != 2 {
		t.Fatalf("FindByIDs() returned %d products, want 2 (the unknown id is skipped)", len(found))
	}
	if found[0].Code != "A-1" || found[1].Code != "B-2" {
		t.Errorf("FindByIDs() = %q and %q, want them ordered by code", found[0].Code, found[1].Code)
	}

	empty, err := store.FindByIDs(ctx, nil)
	if err != nil {
		t.Fatalf("FindByIDs(nil) returned error: %v", err)
	}
	if len(empty) != 0 {
		t.Errorf("FindByIDs(nil) returned %d products, want 0", len(empty))
	}
}

func TestStoreListPagesThroughTheCatalogue(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	for _, code := range []string{"P-1", "P-2", "P-3", "P-4", "P-5"} {
		createProduct(t, ctx, store, code, "Product "+code, 1)
	}

	first, err := store.List(ctx, stock.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(first.Items) != 2 || first.Items[0].Code != "P-1" || first.Items[1].Code != "P-2" {
		t.Fatalf("first page = %+v, want P-1 and P-2", codesOf(first.Items))
	}
	if first.NextCursor == "" {
		t.Fatal("first page has no cursor, want one")
	}

	second, err := store.List(ctx, stock.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 2 || second.Items[0].Code != "P-3" {
		t.Fatalf("second page = %v, want P-3 and P-4", codesOf(second.Items))
	}

	last, err := store.List(ctx, stock.Query{Limit: 2, Cursor: second.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(last.Items) != 1 || last.Items[0].Code != "P-5" {
		t.Fatalf("last page = %v, want only P-5", codesOf(last.Items))
	}
	if last.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", last.NextCursor)
	}
}

// A product registered while someone is paging must not push items from the
// page they already read into the next one, which is what an offset would do.
func TestStoreListIsStableWhenProductsAreRegisteredWhilePaging(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	for _, code := range []string{"P-2", "P-4", "P-6"} {
		createProduct(t, ctx, store, code, "Product "+code, 1)
	}

	first, err := store.List(ctx, stock.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	// Someone registers a product that sorts before everything read so far.
	createProduct(t, ctx, store, "P-1", "Latecomer", 1)

	second, err := store.List(ctx, stock.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 1 || second.Items[0].Code != "P-6" {
		t.Errorf("second page = %v, want only P-6 and no repetition", codesOf(second.Items))
	}
}

func TestStoreListKeepsTheFilterAcrossPages(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "B-1", "Steel bolt", 1)
	createProduct(t, ctx, store, "B-2", "Steel bolt long", 1)
	createProduct(t, ctx, store, "H-1", "Hammer", 1)

	first, err := store.List(ctx, stock.Query{Search: "bolt", Limit: 1})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	second, err := store.List(ctx, stock.Query{Search: "bolt", Limit: 1, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	if len(second.Items) != 1 || second.Items[0].Code != "B-2" {
		t.Errorf("second page = %v, want B-2", codesOf(second.Items))
	}
	if second.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty: the hammer does not match", second.NextCursor)
	}
}

func TestStoreListRejectsACursorItDidNotProduce(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	if _, err := store.List(ctx, stock.Query{Cursor: "not-a-cursor"}); err == nil {
		t.Error("List() accepted a made up cursor, want an error")
	}
}

func codesOf(products []stock.Product) []string {
	codes := make([]string, 0, len(products))
	for _, product := range products {
		codes = append(codes, product.Code)
	}
	return codes
}
