package stock_test

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/thiagodias/korp-invoices/internal/platform/pagination"
	"github.com/thiagodias/korp-invoices/internal/platform/postgres/pgtest"
	"github.com/thiagodias/korp-invoices/internal/stock"
)

func newTestStore(t *testing.T) (context.Context, *stock.Store, *pgxpool.Pool) {
	t.Helper()

	ctx, pool := pgtest.Pool(t, "STOCK_TEST_DATABASE_URL", stock.MigrationsFS, stock.MigrationsDir)
	return ctx, stock.NewStore(pool), pool
}

func createProduct(t *testing.T, ctx context.Context, store *stock.Store, code, description string, balance int) stock.Product {
	t.Helper()

	product, err := stock.NewProduct(code, description, balance)
	if err != nil {
		t.Fatalf("NewProduct() returned error: %v", err)
	}
	created, err := store.Create(ctx, product)
	if err != nil {
		t.Fatalf("Create() returned error: %v", err)
	}
	return created
}

func TestStoreCreateAssignsIdentityAndTimestamps(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	if created.ID == uuid.Nil {
		t.Error("ID is empty, want one generated by the database")
	}
	if created.CreatedAt.IsZero() || created.UpdatedAt.IsZero() {
		t.Error("timestamps are empty, want them filled by the database")
	}
	if created.Code != "P-1" || created.Description != "Steel bolt" || created.Balance != 10 {
		t.Errorf("created = %+v, want the submitted values", created)
	}
}

func TestStoreCreateRejectsDuplicatedCodeIgnoringCase(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	duplicated, err := stock.NewProduct("p-1", "Another bolt", 5)
	if err != nil {
		t.Fatalf("NewProduct() returned error: %v", err)
	}

	if _, err := store.Create(ctx, duplicated); !errors.Is(err, stock.ErrDuplicatedCode) {
		t.Fatalf("Create() error = %v, want ErrDuplicatedCode", err)
	}
}

func TestStoreCreateRejectsNegativeBalanceAtDatabaseLevel(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	// Bypassing the domain constructor proves the database refuses invalid
	// data even if a future code path forgets to validate it.
	_, err := store.Create(ctx, stock.Product{Code: "P-9", Description: "Broken", Balance: -1})
	if err == nil {
		t.Fatal("Create() returned no error for a negative balance, want one")
	}
}

func TestStoreGetByIDAndCode(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	byID, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if byID.ID != created.ID {
		t.Errorf("GetByID() = %v, want %v", byID.ID, created.ID)
	}

	byCode, err := store.GetByCode(ctx, "p-1")
	if err != nil {
		t.Fatalf("GetByCode() returned error: %v", err)
	}
	if byCode.ID != created.ID {
		t.Errorf("GetByCode() = %v, want %v", byCode.ID, created.ID)
	}
}

func TestStoreGetReportsMissingProduct(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	if _, err := store.GetByID(ctx, uuid.New()); !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("GetByID() error = %v, want ErrProductNotFound", err)
	}
	if _, err := store.GetByCode(ctx, "missing"); !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("GetByCode() error = %v, want ErrProductNotFound", err)
	}
}

func TestStoreUpdate(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	created := createProduct(t, ctx, store, "P-1", "Steel bolt", 10)

	created.Description = "Stainless bolt"
	created.Balance = 42

	updated, err := store.Update(ctx, created)
	if err != nil {
		t.Fatalf("Update() returned error: %v", err)
	}
	if updated.Description != "Stainless bolt" || updated.Balance != 42 {
		t.Errorf("updated = %+v, want the new values", updated)
	}
	if !updated.UpdatedAt.After(created.CreatedAt) && !updated.UpdatedAt.Equal(created.CreatedAt) {
		t.Errorf("UpdatedAt = %v, want it refreshed", updated.UpdatedAt)
	}

	stored, err := store.GetByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetByID() returned error: %v", err)
	}
	if stored.Description != "Stainless bolt" || stored.Balance != 42 {
		t.Errorf("stored = %+v, want the new values persisted", stored)
	}
}

func TestStoreUpdateReportsMissingProduct(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	_, err := store.Update(ctx, stock.Product{ID: uuid.New(), Description: "Ghost", Balance: 1})
	if !errors.Is(err, stock.ErrProductNotFound) {
		t.Errorf("Update() error = %v, want ErrProductNotFound", err)
	}
}

func TestStoreListOrdersByCodeAndFilters(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "B-2", "Hammer", 3)
	createProduct(t, ctx, store, "a-1", "Steel bolt", 10)
	createProduct(t, ctx, store, "C-3", "Wrench", 7)

	all, err := store.List(ctx, stock.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	wantOrder := []string{"a-1", "B-2", "C-3"}
	if len(all.Items) != len(wantOrder) {
		t.Fatalf("List() returned %d products, want %d", len(all.Items), len(wantOrder))
	}
	for i, code := range wantOrder {
		if all.Items[i].Code != code {
			t.Errorf("product %d = %q, want %q", i, all.Items[i].Code, code)
		}
	}

	filtered, err := store.List(ctx, stock.Query{Search: "bolt"})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(filtered.Items) != 1 || filtered.Items[0].Code != "a-1" {
		t.Errorf("List(bolt) = %+v, want only the bolt product", filtered.Items)
	}

	byCode, err := store.List(ctx, stock.Query{Search: "c-3"})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(byCode.Items) != 1 || byCode.Items[0].Code != "C-3" {
		t.Errorf("List(c-3) = %+v, want only the wrench product", byCode.Items)
	}
}

func TestStoreListReturnsEmptySliceWhenThereAreNoProducts(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	page, err := store.List(ctx, stock.Query{})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if page.Items == nil {
		t.Fatal("List() returned nil items, want an empty slice")
	}
	if len(page.Items) != 0 {
		t.Errorf("List() returned %d products, want 0", len(page.Items))
	}
	if page.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", page.NextCursor)
	}
}

func TestStoreFindByIDs(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	first := createProduct(t, ctx, store, "A-1", "Steel bolt", 10)
	second := createProduct(t, ctx, store, "B-2", "Hammer", 3)
	createProduct(t, ctx, store, "C-3", "Wrench", 7)

	found, err := store.FindByIDs(ctx, []uuid.UUID{second.ID, first.ID, uuid.New()})
	if err != nil {
		t.Fatalf("FindByIDs() returned error: %v", err)
	}
	if len(found) != 2 {
		t.Fatalf("FindByIDs() returned %d products, want 2 (the unknown id is skipped)", len(found))
	}
	if found[0].Code != "A-1" || found[1].Code != "B-2" {
		t.Errorf("FindByIDs() = %q and %q, want them ordered by code", found[0].Code, found[1].Code)
	}

	empty, err := store.FindByIDs(ctx, nil)
	if err != nil {
		t.Fatalf("FindByIDs(nil) returned error: %v", err)
	}
	if len(empty) != 0 {
		t.Errorf("FindByIDs(nil) returned %d products, want 0", len(empty))
	}
}

func TestStoreListPagesThroughTheCatalogue(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	for _, code := range []string{"P-1", "P-2", "P-3", "P-4", "P-5"} {
		createProduct(t, ctx, store, code, "Product "+code, 1)
	}

	first, err := store.List(ctx, stock.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(first.Items) != 2 || first.Items[0].Code != "P-1" || first.Items[1].Code != "P-2" {
		t.Fatalf("first page = %+v, want P-1 and P-2", codesOf(first.Items))
	}
	if first.NextCursor == "" {
		t.Fatal("first page has no cursor, want one")
	}

	second, err := store.List(ctx, stock.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 2 || second.Items[0].Code != "P-3" {
		t.Fatalf("second page = %v, want P-3 and P-4", codesOf(second.Items))
	}

	last, err := store.List(ctx, stock.Query{Limit: 2, Cursor: second.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(last.Items) != 1 || last.Items[0].Code != "P-5" {
		t.Fatalf("last page = %v, want only P-5", codesOf(last.Items))
	}
	if last.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty on the last page", last.NextCursor)
	}
}

// A product registered while someone is paging must not push items from the
// page they already read into the next one, which is what an offset would do.
func TestStoreListIsStableWhenProductsAreRegisteredWhilePaging(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	for _, code := range []string{"P-2", "P-4", "P-6"} {
		createProduct(t, ctx, store, code, "Product "+code, 1)
	}

	first, err := store.List(ctx, stock.Query{Limit: 2})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	// Someone registers a product that sorts before everything read so far.
	createProduct(t, ctx, store, "P-1", "Latecomer", 1)

	second, err := store.List(ctx, stock.Query{Limit: 2, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(second.Items) != 1 || second.Items[0].Code != "P-6" {
		t.Errorf("second page = %v, want only P-6 and no repetition", codesOf(second.Items))
	}
}

func TestStoreListKeepsTheFilterAcrossPages(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "B-1", "Steel bolt", 1)
	createProduct(t, ctx, store, "B-2", "Steel bolt long", 1)
	createProduct(t, ctx, store, "H-1", "Hammer", 1)

	first, err := store.List(ctx, stock.Query{Search: "bolt", Limit: 1})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	second, err := store.List(ctx, stock.Query{Search: "bolt", Limit: 1, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	if len(second.Items) != 1 || second.Items[0].Code != "B-2" {
		t.Errorf("second page = %v, want B-2", codesOf(second.Items))
	}
	if second.NextCursor != "" {
		t.Errorf("NextCursor = %q, want it empty: the hammer does not match", second.NextCursor)
	}
}

func TestStoreListRejectsACursorItDidNotProduce(t *testing.T) {
	ctx, store, _ := newTestStore(t)

	if _, err := store.List(ctx, stock.Query{Cursor: "not-a-cursor"}); err == nil {
		t.Error("List() accepted a made up cursor, want an error")
	}
}

func codesOf(products []stock.Product) []string {
	codes := make([]string, 0, len(products))
	for _, product := range products {
		codes = append(codes, product.Code)
	}
	return codes
}

func intPtr(value int) *int { return &value }

func TestStoreListFiltersByBalanceRange(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "OUT-1", "Out of stock", 0)
	createProduct(t, ctx, store, "LOW-1", "Almost gone", 2)
	createProduct(t, ctx, store, "FULL-1", "Plenty", 100)

	// The question this filter exists for: what is out of stock?
	empty, err := store.List(ctx, stock.Query{MaxBalance: intPtr(0)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(empty.Items) != 1 || empty.Items[0].Code != "OUT-1" {
		t.Errorf("out of stock = %v, want OUT-1", codesOf(empty.Items))
	}

	low, err := store.List(ctx, stock.Query{MaxBalance: intPtr(5)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(low.Items) != 2 {
		t.Errorf("running out = %v, want OUT-1 and LOW-1", codesOf(low.Items))
	}

	stocked, err := store.List(ctx, stock.Query{MinBalance: intPtr(1)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(stocked.Items) != 2 {
		t.Errorf("in stock = %v, want LOW-1 and FULL-1", codesOf(stocked.Items))
	}

	between, err := store.List(ctx, stock.Query{MinBalance: intPtr(1), MaxBalance: intPtr(5)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(between.Items) != 1 || between.Items[0].Code != "LOW-1" {
		t.Errorf("between = %v, want LOW-1", codesOf(between.Items))
	}
}

func TestStoreListCombinesSearchAndBalance(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "B-1", "Steel bolt", 0)
	createProduct(t, ctx, store, "B-2", "Steel bolt long", 30)
	createProduct(t, ctx, store, "H-1", "Hammer", 0)

	page, err := store.List(ctx, stock.Query{Search: "bolt", MaxBalance: intPtr(0)})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 1 || page.Items[0].Code != "B-1" {
		t.Errorf("filtered = %v, want only the bolt that is out of stock", codesOf(page.Items))
	}
}

func TestStoreListSortsByBalance(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "A-1", "Plenty", 50)
	createProduct(t, ctx, store, "B-1", "Almost gone", 1)
	createProduct(t, ctx, store, "C-1", "Half", 10)

	lowestFirst, err := store.List(ctx, stock.Query{Sort: stock.SortByBalance})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if codes := codesOf(lowestFirst.Items); len(codes) != 3 || codes[0] != "B-1" || codes[2] != "A-1" {
		t.Errorf("order = %v, want the lowest balance first", codes)
	}

	highestFirst, err := store.List(ctx, stock.Query{Sort: stock.SortByBalance, Order: pagination.Descending})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if codes := codesOf(highestFirst.Items); codes[0] != "A-1" {
		t.Errorf("order = %v, want the highest balance first", codes)
	}
}

// Sorting by a column that repeats needs the cursor to carry both the balance
// and the code, or a page boundary between two equal balances loses products.
func TestStoreListPagesThroughEqualBalances(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	for _, code := range []string{"E-1", "E-2", "E-3", "E-4"} {
		createProduct(t, ctx, store, code, "Same balance", 7)
	}

	seen := []string{}
	cursor := ""
	for range 4 {
		page, err := store.List(ctx, stock.Query{Sort: stock.SortByBalance, Limit: 2, Cursor: cursor})
		if err != nil {
			t.Fatalf("List() returned error: %v", err)
		}
		seen = append(seen, codesOf(page.Items)...)
		cursor = page.NextCursor
		if cursor == "" {
			break
		}
	}

	if len(seen) != 4 {
		t.Fatalf("paged through %v, want every product exactly once", seen)
	}
	for index, code := range []string{"E-1", "E-2", "E-3", "E-4"} {
		if seen[index] != code {
			t.Errorf("product %d = %q, want %q", index, seen[index], code)
		}
	}
}

func TestStoreListKeepsFiltersAcrossPages(t *testing.T) {
	ctx, store, _ := newTestStore(t)
	createProduct(t, ctx, store, "L-1", "Low one", 1)
	createProduct(t, ctx, store, "L-2", "Low two", 2)
	createProduct(t, ctx, store, "F-1", "Full", 90)

	first, err := store.List(ctx, stock.Query{MaxBalance: intPtr(5), Limit: 1})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	second, err := store.List(ctx, stock.Query{MaxBalance: intPtr(5), Limit: 1, Cursor: first.NextCursor})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}

	if len(second.Items) != 1 || second.Items[0].Code != "L-2" {
		t.Errorf("second page = %v, want L-2", codesOf(second.Items))
	}
	if second.NextCursor != "" {
		t.Error("the filter was lost while paging: the full product came back")
	}
}

// The listing must never read the whole table into memory, no matter how many
// products match the filters.
func TestStoreListReadsOnlyOnePageOfALargeCatalogue(t *testing.T) {
	ctx, store, pool := newTestStore(t)

	if _, err := pool.Exec(ctx, `
		INSERT INTO products (code, description, balance)
		SELECT 'BULK-' || lpad(number::text, 5, '0'), 'Bulk product ' || number, number % 50
		FROM generate_series(1, 5000) AS number`); err != nil {
		t.Fatalf("seed catalogue: %v", err)
	}

	page, err := store.List(ctx, stock.Query{Limit: 20})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	if len(page.Items) != 20 {
		t.Fatalf("page = %d products, want 20 out of 5000", len(page.Items))
	}

	// With statistics in place, the search has to use the trigram index rather
	// than reading all 5000 rows.
	if _, err := pool.Exec(ctx, `ANALYZE products`); err != nil {
		t.Fatalf("analyze products: %v", err)
	}

	// The listing never falls back to reading the table.
	listing := explain(t, ctx, pool, `
		SELECT id, code, description, balance, created_at, updated_at
		FROM products
		WHERE TRUE
		  AND (code ILIKE '%' || 'BULK-042' || '%' OR description ILIKE '%' || 'BULK-042' || '%')
		ORDER BY upper(code)
		LIMIT 21`)

	if strings.Contains(listing, "Seq Scan") {
		t.Errorf("the search reads every product instead of using an index:\n%s", listing)
	}
}

// A "contains" search cannot use a plain btree index, so the catalogue carries
// trigram indexes for it. Whether the planner picks one is a cost decision that
// depends on the size of the table and on the term, and on a table this size a
// sequential scan is genuinely cheaper; what this test pins down is that the
// index is applicable to the search and returns the right rows, which is what
// makes the plan available once the catalogue grows.
func TestSearchingTheCatalogueCanUseTheTrigramIndex(t *testing.T) {
	ctx, store, pool := newTestStore(t)

	if _, err := pool.Exec(ctx, `
		INSERT INTO products (code, description, balance)
		SELECT 'BULK-' || lpad(number::text, 6, '0'), md5(number::text) || ' part', number % 50
		FROM generate_series(1, 20000) AS number`); err != nil {
		t.Fatalf("seed catalogue: %v", err)
	}
	if _, err := pool.Exec(ctx, `ANALYZE products`); err != nil {
		t.Fatalf("analyze products: %v", err)
	}

	var needle string
	if err := pool.QueryRow(ctx, `SELECT substr(md5('4242'), 1, 8)`).Scan(&needle); err != nil {
		t.Fatalf("read search term: %v", err)
	}

	// Taking the table scan away leaves the plan the index makes possible.
	if _, err := pool.Exec(ctx, `SET enable_seqscan = off`); err != nil {
		t.Fatalf("disable sequential scans: %v", err)
	}
	plan := explain(t, ctx, pool,
		"SELECT id FROM products WHERE description ILIKE '%' || '"+needle+"' || '%'")
	if _, err := pool.Exec(ctx, `SET enable_seqscan = on`); err != nil {
		t.Fatalf("restore sequential scans: %v", err)
	}

	if !strings.Contains(plan, "products_description_search_idx") {
		t.Errorf("the trigram index cannot serve a contains search:\n%s", plan)
	}

	// And the search itself returns what it should.
	page, err := store.List(ctx, stock.Query{Search: needle, Limit: 5})
	if err != nil {
		t.Fatalf("List() returned error: %v", err)
	}
	for _, product := range page.Items {
		if !strings.Contains(product.Description, needle) {
			t.Errorf("product %q does not match the search term %q", product.Description, needle)
		}
	}
}

// explain returns the query plan as text.
func explain(t *testing.T, ctx context.Context, pool *pgxpool.Pool, statement string) string {
	t.Helper()

	rows, err := pool.Query(ctx, "EXPLAIN "+statement)
	if err != nil {
		t.Fatalf("explain: %v", err)
	}
	defer rows.Close()

	var plan strings.Builder
	for rows.Next() {
		var line string
		if err := rows.Scan(&line); err != nil {
			t.Fatalf("read plan: %v", err)
		}
		plan.WriteString(line)
		plan.WriteString("\n")
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("read plan: %v", err)
	}
	return plan.String()
}
